version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
        - 8-1-fpm
        - 8-0-fpm
        - 7-4-fpm
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./data/nginx/enabled:/etc/nginx/conf.d
        - ./data/nginx/snippets:/nginx/snippets
        - ./data/nginx/certs:/nginx/certs
    volumes_from:
        - data

  8-1-fpm:
    build: build/php/8-1
    restart: always
    volumes_from:
        - data

  8-0-fpm:
    build: build/php/8-0
    restart: always
    volumes_from:
        - data

  7-4-fpm:
    build: build/php/7-4
    restart: always
    volumes_from:
        - data

  db:
    image: mysql
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"


  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root # Remove line for production
      PMA_PASSWORD: root # Remove line for production
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    # ports:
    #   - "8080:80"

  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./data/vhosts:/vhosts
      - ./data/tmp:/tmp
